# Jekyll configuration
name: DeconMSn
description: DeconMSn creates spectrum files for tandem mass spectrometry data.
url: https://pnnl-comp-mass-spec.github.io/DeconMSn/

# Google Analytics
google_analytics: G-LXXKP1N66C
